# ========================
# DB Connection Settings
# ========================
jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://walab.handong.edu:3306/W25_22300155?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
jdbc.username=W25_22300155
jdbc.password=Xiz5be

# ========================
# MyBatis Settings (??? ???)
# ========================
mybatis.config-location=classpath:mybatis/mybatis-config.xml
mybatis.mapper-locations=classpath:mybatis/mapper/*.xml

# (??) VO ??? alias ??? ?? ?? ?
mybatis.type-aliases-package=com.hgu.guitar.vo
